name: fastapi-albumes

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-albumes
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - fastapi-db
    environment:
      - DB_SERVER=fastapi-db
      - DB_PORT=5432
      - DB_NAME=albumesdb
      - DB_USER=miguel
      - DB_PASSWORD=1234
  
  fastapi-db:
    image: postgres:15
    container_name: fastapi-db-albumes
    environment:
      POSTGRES_USER: miguel
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: albumesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: